## Essentials of NumPy

In [1]:
# Install package
!pip install numpy

  Using cached numpy-2.3.1-cp312-cp312-macosx_14_0_arm64.whl.metadata (62 kB)
Using cached numpy-2.3.1-cp312-cp312-macosx_14_0_arm64.whl (5.1 MB)


In [2]:
# Import package
import numpy as np

In [3]:
# Convert Python lists to arrays
numbers_list = [1, 2, 3, 4]

# Creating an array from the list
numbers_arr = np.array(numbers_list)
numbers_arr

array([1, 2, 3, 4])

In [4]:
type(numbers_arr)

numpy.ndarray

In [6]:
# Creating an array of floats from the list
numbers_float_arr = np.array(numbers_list, dtype=float)
numbers_float_arr

array([1., 2., 3., 4.])

In [7]:
names_list = [["Reena", "Rachel", "Mercedes"], ["Kumar", "John", "Karel"]]

# Creating an array of strings from the names list
names_arr = np.array(names_list)
names_arr

array([['Reena', 'Rachel', 'Mercedes'],
       ['Kumar', 'John', 'Karel']], dtype='<U8')

In [8]:
# Check the number of dimensions in the array
names_arr.ndim

2

In [9]:
# Get the total number of elements in the names_arr array (rows × columns)
names_arr.size

6

In [13]:
# Create a NumPy array with values starting from 0 up to (but not including) 10, incrementing by 2
range_arr = np.arange(0, 10, 2)
range_arr

array([0, 2, 4, 6, 8])

In [ ]:
# Create a 3x4 NumPy array filled with zeros, with data type float
zeros_arr = np.zeros((3, 4), dtype=float)
zeros_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
# Create a 3x4 NumPy array filled with ones, with data type float
ones_arr = np.ones((3, 4), dtype=float)
ones_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
# Create a random number generator using NumPy's Generator class
random_number_gen = np.random.default_rng()

# Generate a 3x4 array of random integers from 0 (inclusive) to 10 (exclusive)
random_number_gen.integers(0, 10, size=(3, 4))

array([[0, 7, 6, 2],
       [8, 6, 4, 8],
       [1, 0, 6, 2]])

In [37]:
# Create a random number generator with a fixed seed (24) for reproducible results
rng = np.random.default_rng(seed=24)

# Generate a 3x4 array of random floats uniformly distributed in the range [0.0, 1.0)
rng.random((3, 4))

array([[0.33026884, 0.40517732, 0.57473782, 0.50639977],
       [0.56421251, 0.56968731, 0.87411653, 0.08643046],
       [0.74247527, 0.82036726, 0.71216007, 0.40992561]])

In [39]:
# Create a nested list containing two sublists of names
names_list = [["Reena", "Rachel", "Mercedes"], ["Kumar", "John", "Karel"]]

# Convert the nested list into a 2D NumPy array
names_arr = np.array(names_list)
names_arr

array([['Reena', 'Rachel', 'Mercedes'],
       ['Kumar', 'John', 'Karel']], dtype='<U8')

In [40]:
# Select all rows and columns starting from index 1 (i.e., exclude the first column)
# : -> Select all rows
# 1: -> Select columns starting from index 1 to the end
names_arr[:, 1:]

array([['Rachel', 'Mercedes'],
       ['John', 'Karel']], dtype='<U8')

In [41]:
# Create index arrays to select specific elements
select_kumar = np.array([1, 0])
select_mercedes = np.array([0, 2])

# Use fancy indexing to select elements at (1,0) and (0,2): "Kumar" and "Mercedes"
select_kumar_mercedes = names_arr[select_kumar, select_mercedes]
select_kumar_mercedes

array(['Kumar', 'Mercedes'], dtype='<U8')

In [42]:
names_arr[[1, 0], [0, 2]]

array(['Kumar', 'Mercedes'], dtype='<U8')

In [47]:
# Create a 3x3 NumPy array of integers
number_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create a boolean mask where each element is True if it's even, False otherwise
filter_array = number_arr % 2 == 0
print(filter_array)

# Use the boolean mask to filter and return only the even elements from the original array
number_arr[filter_array]

[[False  True False]
 [ True False  True]
 [False  True False]]


array([2, 4, 6, 8])

In [50]:
# Flatten the array using reshape
np.reshape(number_arr, number_arr.size)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
# Create a nested list containing two sublists of names
names_list = [["Reena", "Rachel", "Mercedes"], ["Kumar", "John", "Karel"]]

# Convert the nested list into a 2D NumPy array
names_arr = np.array(names_list)
names_arr

array([['Reena', 'Rachel', 'Mercedes'],
       ['Kumar', 'John', 'Karel']], dtype='<U8')

In [52]:
# Reshape the array from shape (2, 3) to shape (3, 2) without changing data
new_names_arr = np.reshape(names_arr, (3, 2))
new_names_arr

array([['Reena', 'Rachel'],
       ['Mercedes', 'Kumar'],
       ['John', 'Karel']], dtype='<U8')

In [56]:
# Create two NumPy arrays:
# number_arr1 is a 3x3 array
number_arr1 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
# number_arr2 is a 2x3 array
number_arr2 = np.array([[100, 110, 120], [130, 140, 150]])

# Concatenate the two arrays vertically (along axis 0 -> rows)
# Both arrays must have the same number of columns (which they do: 3)
number_arr3 = np.concatenate((number_arr1, number_arr2), axis=0)
number_arr3

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120],
       [130, 140, 150]])

In [57]:
# Create a nested list containing two sublists of names
names_list = [["Reena", "Rachel", "Mercedes"], ["Kumar", "John", "Karel"]]

# Convert the nested list into a 2D NumPy array
names_arr = np.array(names_list)
names_arr

array([['Reena', 'Rachel', 'Mercedes'],
       ['Kumar', 'John', 'Karel']], dtype='<U8')

In [58]:
# using split to split array into two parts
split_one, split_two = np.split(names_arr, 2)

In [59]:
split_one

array([['Reena', 'Rachel', 'Mercedes']], dtype='<U8')

In [99]:
split_two

array([['Kumar', 'John', 'Karel']], dtype='<U8')

In [60]:
# Create two NumPy arrays:
# number_arr1 is a 3x3 array
number_arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# number_arr2 is a 2x3 array
number_arr2 = np.array([[10, 11, 12], [13, 14, 15]])

# Performing a dot product (matrix multiplication) — this will raise an error
# because the number of columns in number_arr1 (3) does not match
# the number of rows in number_arr2 (2), which is required for np.dot
np.dot(number_arr1, number_arr2)

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [63]:
number_arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [64]:
number_arr2.transpose()

array([[10, 13],
       [11, 14],
       [12, 15]])

In [65]:
# Fix: Transpose number_arr2 to shape (3, 2), now dot product is valid
np.dot(number_arr1, number_arr2.transpose())

array([[ 68,  86],
       [167, 212],
       [266, 338]])

In [66]:
# Create two 2x3 NumPy arrays
number_arr1 = np.array([[1, 2, 4], [6, 7, 8]])
number_arr2 = np.array([[3, 3, 6], [4, 5, 7]])

# Add the two arrays element-wise (i.e., same-position elements are added together)
np.add(number_arr1, number_arr2)

array([[ 4,  5, 10],
       [10, 12, 15]])

In [121]:
# Subtracting two arrays
np.subtract(number_arr1, number_arr2)

array([[-2, -1, -2],
       [ 2,  2,  1]])

In [122]:
# multiplying two arrays
np.multiply(number_arr1, number_arr2)

array([[ 3,  6, 24],
       [24, 35, 56]])

In [123]:
# Dividing two arrays
np.divide(number_arr1, number_arr2)

array([[0.33333333, 0.66666667, 0.66666667],
       [1.5       , 1.4       , 1.14285714]])

In [73]:
# Create a 2x3 NumPy array
number_arr1 = np.array([[3, 3, 6], [4, 5, 7]])

# Raise each element of the array to the power of 2 (element-wise squaring)
np.power(number_arr1, 2)

array([[ 9,  9, 36],
       [16, 25, 49]])

In [74]:
# Calculating the square-root of array
np.sqrt(number_arr1)

array([[1.73205081, 1.73205081, 2.44948974],
       [2.        , 2.23606798, 2.64575131]])

In [75]:
# Create a 2x3 NumPy array
number_arr1 = np.array([[3, 3, 6], [4, 5, 7]])

# Calculate the mean (average) of each row in the array
# axis=1 means the operation is performed across columns (i.e., row-wise)
np.mean(number_arr1, axis=1)

array([4.        , 5.33333333])

In [76]:
# Create a 2x3 NumPy array
number_arr1 = np.array([[3, 3, 6], [4, 5, 7]])

np.mean(number_arr1, axis=0)

array([3.5, 4. , 6.5])

In [77]:
# Create a 2x3 NumPy array
number_arr1 = np.array([[3, 3, 6], [4, 5, 7]])

# Calculate the median (middle value) of each row in the array
# axis=1 means the operation is applied row-wise (across columns)
np.median(number_arr1, axis=1)

array([3., 5.])

In [78]:
# Create a 2x3 NumPy array
number_arr1 = np.array([[3, 3, 6], [4, 5, 7]])

# Calculate the median (middle value) of each row in the array
# axis=0 means the operation is applied column-wise (across rows)
np.median(number_arr1, axis=0)

array([3.5, 4. , 6.5])

In [79]:
# Create a 2x3 NumPy array
number_arr1 = np.array([[3, 3, 6], [4, 5, 7]])

# Calculate the standard deviation of each column in the array
# axis=0 means the operation is applied column-wise (down the rows)
np.std(number_arr1, axis=0)

array([0.5, 1. , 0.5])

In [81]:
# Create a 2x3 NumPy array
number_arr1 = np.array([[3, 3, 6], [4, 5, 7]])

# Calculate the standard deviation of each row in the array
# axis=1 means the operation is applied row-wise (down the rows)
np.std(number_arr1, axis=1)

array([1.41421356, 1.24721913])

In [82]:
# Create a 2x3 NumPy array
number_arr1 = np.array([[3, 3, 6], [4, 5, 7]])

# Calculate the variance of each column in the array
# axis=0 means the operation is applied column-wise (down the rows)
np.var(number_arr1, axis=0)

array([0.25, 1.  , 0.25])

In [83]:
# Create a 2x3 NumPy array
number_arr1 = np.array([[3, 3, 6], [4, 5, 7]])

# Calculate the variance of each row in the array
# axis=1 means the operation is applied row-wise (across columns)
np.var(number_arr1, axis=1)

array([2.        , 1.55555556])

In [84]:
# Create a 2x3 NumPy array
number_arr1 = np.array([[3, 3, 6], [4, 5, 7]])

# Calculate the minimum value in each column of the array
# axis=0 means the operation is applied column-wise (down the rows)
np.min(number_arr1, axis=0)

array([3, 3, 6])

In [85]:
# Create a 2x3 NumPy array
number_arr1 = np.array([[3, 3, 6], [4, 5, 7]])

# Calculate the minimum value in each column of the array
# axis=1 means the operation is applied row-wise (across columns)
np.min(number_arr1, axis=1)

array([3, 4])

In [86]:
# Create a 2x3 NumPy array
number_arr1 = np.array([[3, 3, 6], [4, 5, 7]])

# Calculate the maximum value in the entire array (all elements)
# axis=None means the operation considers the flattened array
np.max(number_arr1, axis=None)

np.int64(7)

In [87]:
# Create a 2x3 NumPy array
number_arr1 = np.array([[3, 3, 6], [4, 5, 7]])

# Calculate the maximum value in the entire array (all elements)
# axis=0 means the operation considers the flattened array
np.max(number_arr1, axis=0)

array([4, 5, 7])

In [88]:
# Create a 2x3 NumPy array
number_arr1 = np.array([[3, 3, 6], [4, 5, 7]])

# Calculate the maximum value in the entire array (all elements)
# axis=1 means the operation considers the flattened array
np.max(number_arr1, axis=1)

array([6, 7])

In [22]:
# pyhton list
list = [["deekman", "seedo", "mersing"],["xoverro", "angelo", "chiara"]]

# Python list -> Numpy array
name_arr = np.array(list)

name_arr

array([['deekman', 'seedo', 'mersing'],
       ['xoverro', 'angelo', 'chiara']], dtype='<U7')

In [23]:
# first : => Rows
# second : => columns

# Row, Column
# name_arr[:, 2]

name_arr[[0,0], [1,0]]

array(['seedo', 'deekman'], dtype='<U7')

In [30]:
name_arr[[0,0]]

array([['deekman', 'seedo', 'mersing'],
       ['deekman', 'seedo', 'mersing']], dtype='<U7')

In [ ]:
# [0,0] = Row 0 (twice)
# [1,0] = Column 1, 0 
name_arr[[0,0], [1,0]]

array(['seedo', 'deekman'], dtype='<U7')

In [ ]:
name_arr[[0,0], [1,0]]

In [17]:
name_arr

array([['deekman', 'seedo', 'mersing'],
       ['xoverro', 'angelo', 'chiara']], dtype='<U7')

In [18]:
name_arr[0,0]

np.str_('deekman')

In [19]:
name_arr[[0,0]]

array([['deekman', 'seedo', 'mersing'],
       ['deekman', 'seedo', 'mersing']], dtype='<U7')